import {
  FileText, Layers, Mail, Calendar, Globe, GitBranch, Zap, Users,
  Headphones, CreditCard, Database, Plus, Brain, Code2, BarChart3,
  Sparkles, LayoutGrid,
} from "lucide-react";

import type { OmniPackage } from "./types";

export const PACKAGES: OmniPackage[] = [
  {
    id: "1",
    key: "engine.document",
    name: "Document Engine",
    description: "Block-based document engine with real-time collaboration",
    kind: "engine",
    trustLevel: "first_party",
    version: "3.2.0",
    author: "OmniOS",
    downloads: 94000,
    stars: 4800,
    tags: ["productivity", "collaborative"],
    color: "#6366F1",
    icon: FileText,
    featured: true,
  },
  {
    id: "2",
    key: "connector.hubspot",
    name: "HubSpot Connector",
    description: "Full HubSpot CRM sync — contacts, deals, pipeline",
    kind: "connector",
    trustLevel: "verified_partner",
    version: "2.1.0",
    author: "HubSpot",
    downloads: 61000,
    stars: 4200,
    tags: ["crm", "sales"],
    color: "#10B981",
    icon: Globe,
    featured: true,
  },
  {
    id: "3",
    key: "agent.lead_scorer",
    name: "Lead Scorer Agent",
    description: "AI lead scoring 0-100 using company data + behavior",
    kind: "agent",
    trustLevel: "first_party",
    version: "1.0.0",
    author: "OmniOS",
    downloads: 28000,
    stars: 3200,
    tags: ["ai", "sales", "scoring"],
    color: "#8B5CF6",
    icon: Brain,
    featured: true,
  },
  {
    id: "4",
    key: "app.crm",
    name: "CRM Application",
    description: "Complete CRM application: contacts, pipeline, email",
    kind: "app",
    trustLevel: "first_party",
    version: "4.0.0",
    author: "OmniOS",
    downloads: 45000,
    stars: 4600,
    tags: ["crm", "sales", "productivity"],
    color: "#3B82F6",
    icon: Users,
    featured: true,
  },
  {
    id: "5",
    key: "engine.sheet",
    name: "Sheet Engine",
    description: "Real-time collaborative spreadsheet with formulas",
    kind: "engine",
    trustLevel: "first_party",
    version: "2.8.0",
    author: "OmniOS",
    downloads: 52000,
    stars: 3800,
    tags: ["productivity", "data"],
    color: "#6366F1",
    icon: Layers,
  },
  {
    id: "6",
    key: "engine.email",
    name: "Email Engine",
    description: "Unified email management with threading and labels",
    kind: "engine",
    trustLevel: "first_party",
    version: "2.5.0",
    author: "OmniOS",
    downloads: 38000,
    stars: 3400,
    tags: ["communication", "email"],
    color: "#6366F1",
    icon: Mail,
  },
  {
    id: "7",
    key: "engine.calendar",
    name: "Calendar Engine",
    description: "Multi-timezone calendar with scheduling and invites",
    kind: "engine",
    trustLevel: "first_party",
    version: "2.3.0",
    author: "OmniOS",
    downloads: 35000,
    stars: 3100,
    tags: ["scheduling", "time"],
    color: "#6366F1",
    icon: Calendar,
  },
  {
    id: "8",
    key: "engine.media",
    name: "Media Engine",
    description: "Image and video processing with optimization",
    kind: "engine",
    trustLevel: "first_party",
    version: "1.9.0",
    author: "OmniOS",
    downloads: 22000,
    stars: 2400,
    tags: ["media", "processing"],
    color: "#6366F1",
    icon: Sparkles,
  },
  {
    id: "9",
    key: "engine.form",
    name: "Form Engine",
    description: "Dynamic form builder with validation and submissions",
    kind: "engine",
    trustLevel: "first_party",
    version: "2.1.0",
    author: "OmniOS",
    downloads: 28000,
    stars: 2800,
    tags: ["forms", "input"],
    color: "#6366F1",
    icon: Plus,
  },
  {
    id: "10",
    key: "engine.chat",
    name: "Chat Engine",
    description: "Real-time messaging with threads and rich media",
    kind: "engine",
    trustLevel: "first_party",
    version: "2.0.0",
    author: "OmniOS",
    downloads: 31000,
    stars: 2900,
    tags: ["communication", "chat"],
    color: "#6366F1",
    icon: Brain,
  },
  {
    id: "11",
    key: "connector.slack",
    name: "Slack Connector",
    description: "Bidirectional Slack sync with message threading",
    kind: "connector",
    trustLevel: "verified_partner",
    version: "3.2.0",
    author: "Slack",
    downloads: 58000,
    stars: 4100,
    tags: ["communication", "integration"],
    color: "#10B981",
    icon: FileText,
  },
  {
    id: "12",
    key: "connector.gmail",
    name: "Gmail Connector",
    description: "Gmail sync with label management and drafts",
    kind: "connector",
    trustLevel: "verified_partner",
    version: "2.8.0",
    author: "Google",
    downloads: 49000,
    stars: 3900,
    tags: ["email", "integration"],
    color: "#10B981",
    icon: Mail,
  },
  {
    id: "13",
    key: "connector.stripe",
    name: "Stripe Connector",
    description: "Payment processing and invoice management",
    kind: "connector",
    trustLevel: "verified_partner",
    version: "2.5.0",
    author: "Stripe",
    downloads: 42000,
    stars: 3700,
    tags: ["payments", "finance"],
    color: "#10B981",
    icon: CreditCard,
  },
  {
    id: "14",
    key: "connector.notion",
    name: "Notion Connector",
    description: "Notion database sync and page management",
    kind: "connector",
    trustLevel: "community_verified",
    version: "1.9.0",
    author: "Community",
    downloads: 35000,
    stars: 3200,
    tags: ["docs", "integration"],
    color: "#10B981",
    icon: Database,
  },
  {
    id: "15",
    key: "connector.github",
    name: "GitHub Connector",
    description: "Repository monitoring and PR notifications",
    kind: "connector",
    trustLevel: "verified_partner",
    version: "2.3.0",
    author: "GitHub",
    downloads: 38000,
    stars: 3500,
    tags: ["code", "integration"],
    color: "#10B981",
    icon: GitBranch,
  },
  {
    id: "16",
    key: "connector.linear",
    name: "Linear Connector",
    description: "Issue tracking and project sync",
    kind: "connector",
    trustLevel: "verified_partner",
    version: "1.8.0",
    author: "Linear",
    downloads: 24000,
    stars: 2800,
    tags: ["project", "integration"],
    color: "#10B981",
    icon: Zap,
  },
  {
    id: "17",
    key: "connector.salesforce",
    name: "Salesforce Connector",
    description: "Salesforce data sync with custom objects",
    kind: "connector",
    trustLevel: "verified_partner",
    version: "3.1.0",
    author: "Salesforce",
    downloads: 32000,
    stars: 3400,
    tags: ["crm", "integration"],
    color: "#10B981",
    icon: Users,
  },
  {
    id: "18",
    key: "connector.zendesk",
    name: "Zendesk Connector",
    description: "Support ticket management and customer sync",
    kind: "connector",
    trustLevel: "verified_partner",
    version: "2.2.0",
    author: "Zendesk",
    downloads: 27000,
    stars: 3000,
    tags: ["support", "integration"],
    color: "#10B981",
    icon: Headphones,
  },
  {
    id: "19",
    key: "connector.xero",
    name: "Xero Connector",
    description: "Accounting sync and invoice automation",
    kind: "connector",
    trustLevel: "verified_partner",
    version: "1.7.0",
    author: "Xero",
    downloads: 18000,
    stars: 2500,
    tags: ["finance", "integration"],
    color: "#10B981",
    icon: CreditCard,
  },
  {
    id: "20",
    key: "connector.docusign",
    name: "DocuSign Connector",
    description: "E-signature management and document automation",
    kind: "connector",
    trustLevel: "verified_partner",
    version: "1.6.0",
    author: "DocuSign",
    downloads: 15000,
    stars: 2200,
    tags: ["documents", "integration"],
    color: "#10B981",
    icon: FileText,
  },
  {
    id: "21",
    key: "connector.twilio",
    name: "Twilio Connector",
    description: "SMS and voice communication platform",
    kind: "connector",
    trustLevel: "verified_partner",
    version: "2.0.0",
    author: "Twilio",
    downloads: 21000,
    stars: 2700,
    tags: ["communication", "integration"],
    color: "#10B981",
    icon: Mail,
  },
  {
    id: "22",
    key: "connector.shopify",
    name: "Shopify Connector",
    description: "E-commerce and order management sync",
    kind: "connector",
    trustLevel: "verified_partner",
    version: "2.4.0",
    author: "Shopify",
    downloads: 19000,
    stars: 2600,
    tags: ["ecommerce", "integration"],
    color: "#10B981",
    icon: BarChart3,
  },
  {
    id: "23",
    key: "agent.summarizer",
    name: "Summarizer Agent",
    description: "Generate summaries from documents and meetings",
    kind: "agent",
    trustLevel: "first_party",
    version: "1.4.0",
    author: "OmniOS",
    downloads: 19000,
    stars: 2400,
    tags: ["ai", "productivity"],
    color: "#8B5CF6",
    icon: Brain,
  },
  {
    id: "24",
    key: "agent.classifier",
    name: "Classifier Agent",
    description: "Automatic document and email classification",
    kind: "agent",
    trustLevel: "first_party",
    version: "1.2.0",
    author: "OmniOS",
    downloads: 14000,
    stars: 1800,
    tags: ["ai", "automation"],
    color: "#8B5CF6",
    icon: Code2,
  },
  {
    id: "25",
    key: "agent.sentiment",
    name: "Sentiment Analyzer",
    description: "Analyze sentiment from text and customer feedback",
    kind: "agent",
    trustLevel: "community_verified",
    version: "1.1.0",
    author: "Community",
    downloads: 11000,
    stars: 1600,
    tags: ["ai", "analytics"],
    color: "#8B5CF6",
    icon: Sparkles,
  },
  {
    id: "26",
    key: "agent.extractor",
    name: "Data Extractor",
    description: "Extract structured data from unstructured content",
    kind: "agent",
    trustLevel: "first_party",
    version: "1.3.0",
    author: "OmniOS",
    downloads: 16000,
    stars: 2100,
    tags: ["ai", "data"],
    color: "#8B5CF6",
    icon: Code2,
  },
  {
    id: "27",
    key: "agent.translator",
    name: "Translator Agent",
    description: "Multi-language translation with context awareness",
    kind: "agent",
    trustLevel: "community",
    version: "1.0.0",
    author: "Community",
    downloads: 8000,
    stars: 1200,
    tags: ["ai", "language"],
    color: "#8B5CF6",
    icon: Globe,
  },
  {
    id: "28",
    key: "agent.code_gen",
    name: "Code Generator",
    description: "Generate code snippets from natural language",
    kind: "agent",
    trustLevel: "ai_generated",
    version: "0.9.0",
    author: "AI Generated",
    downloads: 6000,
    stars: 900,
    tags: ["ai", "code"],
    color: "#8B5CF6",
    icon: Code2,
  },
  {
    id: "29",
    key: "surface.crm_table",
    name: "CRM Table Surface",
    description: "Advanced table view for contact and deal management",
    kind: "surface",
    trustLevel: "first_party",
    version: "2.0.0",
    author: "OmniOS",
    downloads: 22000,
    stars: 2200,
    tags: ["ui", "crm"],
    color: "#EC4899",
    icon: LayoutGrid,
  },
  {
    id: "30",
    key: "surface.kanban",
    name: "Kanban Surface",
    description: "Drag-and-drop kanban boards for workflow management",
    kind: "surface",
    trustLevel: "first_party",
    version: "1.9.0",
    author: "OmniOS",
    downloads: 18000,
    stars: 1900,
    tags: ["ui", "project"],
    color: "#EC4899",
    icon: Layers,
  },
  {
    id: "31",
    key: "surface.analytics_dash",
    name: "Analytics Dashboard",
    description: "Real-time metrics and chart visualization surface",
    kind: "surface",
    trustLevel: "first_party",
    version: "1.7.0",
    author: "OmniOS",
    downloads: 15000,
    stars: 1700,
    tags: ["ui", "analytics"],
    color: "#EC4899",
    icon: BarChart3,
  },
  {
    id: "32",
    key: "surface.form_builder",
    name: "Form Builder Surface",
    description: "Visual form builder with conditional logic",
    kind: "surface",
    trustLevel: "first_party",
    version: "1.5.0",
    author: "OmniOS",
    downloads: 12000,
    stars: 1400,
    tags: ["ui", "forms"],
    color: "#EC4899",
    icon: Plus,
  },
  {
    id: "33",
    key: "surface.invoice",
    name: "Invoice Surface",
    description: "Beautiful invoice generation and preview",
    kind: "surface",
    trustLevel: "community_verified",
    version: "1.3.0",
    author: "Community",
    downloads: 9000,
    stars: 1100,
    tags: ["ui", "finance"],
    color: "#EC4899",
    icon: CreditCard,
  },
  {
    id: "34",
    key: "surface.portal",
    name: "Portal Surface",
    description: "Client-facing portal and knowledge base template",
    kind: "surface",
    trustLevel: "community",
    version: "1.1.0",
    author: "Community",
    downloads: 6000,
    stars: 800,
    tags: ["ui", "client"],
    color: "#EC4899",
    icon: Globe,
  },
  {
    id: "35",
    key: "app.invoicing",
    name: "Invoicing App",
    description: "Complete invoicing and billing management",
    kind: "app",
    trustLevel: "first_party",
    version: "3.2.0",
    author: "OmniOS",
    downloads: 28000,
    stars: 2600,
    tags: ["finance", "automation"],
    color: "#3B82F6",
    icon: CreditCard,
  },
  {
    id: "36",
    key: "app.hr_ops",
    name: "HR Operations App",
    description: "HR management with payroll and benefits",
    kind: "app",
    trustLevel: "first_party",
    version: "2.5.0",
    author: "OmniOS",
    downloads: 18000,
    stars: 2000,
    tags: ["hr", "people"],
    color: "#3B82F6",
    icon: Users,
  },
  {
    id: "37",
    key: "app.support_desk",
    name: "Support Desk App",
    description: "Customer support ticketing and knowledge base",
    kind: "app",
    trustLevel: "first_party",
    version: "2.3.0",
    author: "OmniOS",
    downloads: 16000,
    stars: 1800,
    tags: ["support", "customer"],
    color: "#3B82F6",
    icon: Headphones,
  },
  {
    id: "38",
    key: "app.ecommerce",
    name: "E-Commerce App",
    description: "Complete e-commerce platform with storefront",
    kind: "app",
    trustLevel: "verified_partner",
    version: "2.1.0",
    author: "Community",
    downloads: 12000,
    stars: 1400,
    tags: ["ecommerce", "sales"],
    color: "#3B82F6",
    icon: BarChart3,
  },
  {
    id: "39",
    key: "app.legal_ops",
    name: "Legal Operations",
    description: "Contract management and legal document workflow",
    kind: "app",
    trustLevel: "community_verified",
    version: "1.8.0",
    author: "Community",
    downloads: 8000,
    stars: 1000,
    tags: ["legal", "documents"],
    color: "#3B82F6",
    icon: FileText,
  },
  {
    id: "40",
    key: "app.dev_tools",
    name: "Developer Tools",
    description: "Development utilities and API management",
    kind: "app",
    trustLevel: "ai_generated",
    version: "1.5.0",
    author: "AI Generated",
    downloads: 5000,
    stars: 600,
    tags: ["dev", "tools"],
    color: "#3B82F6",
    icon: Code2,
  },
];
